---
title: "Commercial"
---

In 2020, I attended the World Economic Forum in Davos and the Enterprise Applications of the R Language (EARL) conference; at both events, I spoke about the planetary emergency and how using data to predict biodiversity loss can help guide us into a more sustainable future. Both events generated interest and inquiries from the commercial and non-profit sectors. Over a number of international events since then, the commercial need for robust, scientific data on biodiversity impacts---along with the ability to project change into the future---has only become clearer.

In response to this growing need, the Natural History Museum has supported the Biodiversity Futures Lab and a number of others in the museum in our efforts to provide biodiversity data packets and biodiversity knowledge to support sustainable business. The main aim is impact; we want to help companies make more sustainable choices. Any funds raised go back into the NHM.

I have developed a [Reproducible Analytical Pipeline](https://analysisfunction.civilservice.gov.uk/support/reproducible-analytical-pipelines/) in R to produce robust data on biodiversity indicators, particularly the Biodiversity Intactness Index. This pipeline allows us to respond more quickly to data requests, while ensuring reproducibility. I also lead on the improvements in statistical methodology and data enhancements.

We have also been engaging with the Task Force for Nature Related Financial Disclosure and others.
