---
title: "Engagement"
---

It's important to me that I share my science with the wider world. Here are some examples of the engagement work I do:

-   I co-wrote a chapter in [The Climate Book](https://www.penguin.co.uk/books/446610/the-climate-book-by-thunberg-greta/9780241547472) by Greta Thunberg.

-   A panel discussion with Greta Thunberg. This was a high profile event as part of The Climate Book launch. As well as engaging with students on the day, the event was also packaged into a set of learning material for students and was later released on [YouTube](https://www.youtube.com/watch?v=_IWnB4gWjP0) where I was available to answer questions.

-   After the release of the Dasgupta Review, to which my work contributed, I took part in an [online panel discussion](https://www.youtube.com/watch?v=eg3Spw0C-g8) and Q&A for the Our Broken Planet Series.

-   I've worked many times with the International Partnerships team and Our Broken Planet at the NHM to engage with young activists, including panel discussions (at the NHM and COP26), Generation Hope and the Climate Cafe, including a [podcast interview](https://www.edie.net/sustainability-uncovered-podcast-episode-2-cop27-reflections-hydrogen-powered-breweries-and-a-youth-climate-cafe/).

-   At COP26 in 2021 I participated in a number of panel discussions both at the Nature Bar and the New York Times Climate Hub.

-   At COP15 in 2022, I took part in a public-facing panel discussion (Bringing Data to Life in the Biodiversity Crisis: a Discussion Between Artists and Scientists) at The Biosphere/La Biosphère (Montreal museum dedicated to the environment).

-   In 2020, I was accepted for a talk at the World Economic Forum in Davos on Protecting Biodiversity with Predictive Technology, where I presented my work allowing for annual, high resolution estimates of the health of biodiversity on land and how such data could be used to help companies make more sustainable choices (De Palma et al, 2021).

-   In 2019, I was named one of the World Economic Forum's Young Scientists of the Year and was invited to talk about the planetary emergency in a [Global Situation Space Scene Setter](https://www.youtube.com/watch?v=R0QW79IuQng&t=760s) at the World Economic Forum Annual Meeting of the New Champions, Dalian.

-   I have been interviewed by the press many times (written, radio and TV, including including Sky News, BBC World News, ITV News).
