---
title: "Science"
---

My full publication list can be found on my [Google Scholar](https://goo.gl/PgXiLf) or [ORCID](https://orcid.org/0000-0002-5345-4917) page.

Over the past few years, my scientific research has mostly focused on improving the statistical methodology behind the [Biodiversity Intactness Index](https://www.nhm.ac.uk/our-science/data/biodiversity-indicators/what-is-the-biodiversity-intactness-index.html#:\~:text=The%20BII%20is%20an%20estimated,granular%20and%20global%20biodiversity%20targets.): a powerful indicator of the health of nature, that can assess the current state of biodiversity as well as project into the future under different scenarios.

My current area of interest is using our high-resolution biodiversity indicators to assess inequality in access to high-quality green space. I'm exploring this in the UK context in detail, and am working on a less detailed, global person-centered indicator of biodiversity health.

I'm also working on [The National Education Nature Park project](https://www.educationnaturepark.org.uk), funded by the Department for Education. I'm leading a work package to investigate how different local conservation interventions impact biodiversity, using this data to help schools, teachers and students to decide on which intervention to put into place. I also plan to explore how we can use biodiversity data gathered by the students to develop new online tools for delivering other aspects of the curriculum (e.g. biology, maths, computer science, geography). Not all people are willing or able to do 'hands-on' conservation work; but through data we can find another way to engage students with the natural world.
